---
title: "lab9"
format:
  html:
    embed-resources: true
editor: visual
---

## Intro

```{r}
# install.packages(c("RSQLite", "DBI"))

library(RSQLite)
library(DBI)

# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
doctor <- read.csv("https://raw.githubusercontent.com/dmcable/BIOSTAT620W26/main/data/hospital/doctor.csv")
visit <- read.csv("https://raw.githubusercontent.com/dmcable/BIOSTAT620W26/main/data/hospital/visit.csv")
patient <- read.csv("https://raw.githubusercontent.com/dmcable/BIOSTAT620W26/main/data/hospital/patient.csv")
payment <- read.csv("https://raw.githubusercontent.com/dmcable/BIOSTAT620W26/main/data/hospital/payment.csv")

# Copy data.frames to database
dbWriteTable(con, "doctor", doctor)
dbWriteTable(con, "visit", visit)
dbWriteTable(con, "patient", patient)
dbWriteTable(con, "payment", payment)

```

## 1

```{sql connection=con}
SELECT doctor_id, first_name, last_name
FROM doctor
ORDER BY last_name, first_name;
```

## 2

```{sql connection=con}
SELECT doctor_id, first_name, last_name
FROM doctor
WHERE last_name IN ('WILLIAMS', 'DAVIS');
```

## 3

```{sql connection=con}
SELECT DISTINCT patient_id
FROM visit
WHERE date(visit_start_date) = '2005-07-05';

```

## 4.1

```{sql connection=con}
SELECT *
FROM payment
WHERE amount IN (199, 799, 999);
```

## 4.2

```{sql connection=con}
SELECT *
FROM payment
WHERE amount > 500;
```

## 4.3

```{sql connection=con}
SELECT *
FROM payment
WHERE amount > 500 AND amount < 800;
```

## 5

```{sql connection=con}
SELECT payment.payment_id, payment.amount
FROM payment
INNER JOIN patient
ON payment.patient_id = patient.patient_id
WHERE patient.last_name = 'DAVIS';
```

## 6.1

```{sql connection=con}
SELECT COUNT(*)
FROM visit;
```

## 6.2

```{sql connection=con}
SELECT patient_id, COUNT(*)
FROM visit
GROUP BY patient_id;
```

## 6.3

```{sql connection=con}
SELECT patient_id, COUNT(*)
FROM visit
GROUP BY patient_id
ORDER BY COUNT(*) DESC;
```

## 6.4

```{sql connection=con}
SELECT patient_id, COUNT(*)
FROM visit
GROUP BY patient_id
HAVING COUNT(*) >= 40
ORDER BY COUNT(*) DESC;
```

## 7

```{sql connection=con}
SELECT 
    MAX(amount),
    MIN(amount),
    AVG(amount),
    SUM(amount)
FROM payment;
```

## 7.1

```{sql connection=con}
SELECT 
    patient_id,
    MAX(amount),
    MIN(amount),
    AVG(amount),
    SUM(amount)
FROM payment
GROUP BY patient_id;
```

## 7.2

```{sql connection=con}
SELECT 
    patient_id,
    MAX(amount),
    MIN(amount),
    AVG(amount),
    SUM(amount)
FROM payment
GROUP BY patient_id
HAVING COUNT(*) > 5;
```

## 8.1

```{sql connection=con}
SELECT 
    doctor.doctor_id,
    doctor.first_name,
    doctor.last_name,
    AVG(julianday(visit.visit_end_date) - julianday(visit.visit_start_date)) AS avg_visit_length
FROM doctor
JOIN visit
ON doctor.doctor_id = visit.doctor_id
GROUP BY doctor.doctor_id;
```

## 8.2

```{sql connection=con}
SELECT 
    doctor.first_name,
    doctor.last_name,
    AVG(julianday(visit.visit_end_date) - julianday(visit.visit_start_date)) AS avg_visit_length
FROM doctor
JOIN visit
ON doctor.doctor_id = visit.doctor_id
GROUP BY doctor.doctor_id
ORDER BY avg_visit_length DESC
LIMIT 5;

```

```{sql connection=con}
SELECT
    doctor.first_name,
    doctor.last_name,
    AVG(julianday(visit.visit_end_date) - julianday(visit.visit_start_date)) AS avg_visit_length
FROM doctor
JOIN visit
ON doctor.doctor_id = visit.doctor_id
GROUP BY doctor.doctor_id
ORDER BY avg_visit_length ASC
LIMIT 5;
```

# **Cleanup**

```{r}
dbDisconnect(con)
```
